### ISSUE TITLE
Is there a way to connect Article-format-template with a Quarto book project? 

### ISSUE THREAD

**Issue by aito123** [quarto-journals/article-format-template#8]
Hello, thanks for this template.

I was deciding what would be the appropiate way to adapt my MS Word thesis to Quarto. At first, I was trying to understand article-format-template to adapt it to my university institution template but then i remembered that Quarto also has the option to include multiple qmd scripts in a book project.

So then I thought, is it possible to adapt article-format-template to a Quarto book project .yml ? If so, how could it be done? I hope this question makes sense in the Quarto landscape.

Thanks again, and let me know.

**Comment by jrfep** [comment]
I faced a similar problem, I had my code structured in different scripts and used the [quarto book ](https://quarto.org/docs/books/) format to organise the content into a HTML document, but ran into some problems when I wanted to use a template for pdf output as an article. 

If the [pdf styles](https://quarto.org/docs/books/book-output.html#pdf-styles) for the book output do not work for you, you can try to mimic the book .yml file with a .qmd file using the `include` command to organise the content:

```
---
title: "Awesome title"

bibliography: 
  - references.bib
csl: style.csl

execute:
  echo: false

format:
  YourJournalFormat-pdf
---

# Abstract

This is a short abstract before I include the section content.

{{< include intro.qmd >}}
{{< include section1.qmd >}}
{{< include section2.qmd >}}

# References

::: {#refs}
:::
```

**Comment by sgolde13** [comment]
I have a similar problem, but specifically I'm hoping to change the author formatting to emulate [JSS](https://github.com/quarto-journals/jss) in a book html. I'm using the [book-html](https://github.com/juba/bookup-html) custom formatting extension.

My _quarto.yml looks like:
```
project:
  type: book

format:
  bookup-html:
    html-math-method: katex
    toc: true
    toc-depth: 3
    callout-appearance: default
```

But even when I try using the jss-html it does not change the author formatting at all.
```
project:
  type: book

format:
  bookup-html:
    html-math-method: katex
    toc: true
    toc-depth: 3
    callout-appearance: default
  jss-html: default
```

Unfortunately, I don't know where to go from here. There is not a lot of documentation about including author section formatting to quarto books in html format.
